name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js (Explicit Version)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x # Specify a fixed version for consistency
          cache: "pnpm"

      - name: Set up pnpm (using npm install -g)
        run: npm install -g pnpm@latest # Install pnpm globally

      - name: Add pnpm to PATH (Important!)
        run: echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build the extension
        run: pnpm build

      - name: Package the extension into a zip artifact
        run: pnpm package

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
