name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pnpm
        run: npm install -g pnpm@9.15.2

      - name: Install projects deps
        run: pnpm install

      - name: Build the extension into a zip artifact
        run: pnpm build

      - name: List files after build (debug)
        run: ls -l build/ # see if the zip is there.

      - name: Package the extension into a zip artifact
        run: pnpm package

      - name: List files after package (debug)
        run: ls -l build/ # or wherever you expect the zip

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
